name: flutter_story_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Page transition animation
  circular_reveal_animation: ^1.1.5
  # Blocs to manage states
  flutter_bloc: ^3.1.0
  json_annotation: ^3.0.1
  # Rest API
  dio: ^3.0.9
  retrofit: 1.0.1+1
  # Logger
  logger: 0.8.3
  equatable: 1.0.3
  # Shared preferences
  shared_preferences: 0.5.6+1
  # Service locator
  get_it: ^2.0.1
  # Remote API to test connection
  data_connection_checker: ^0.3.4
  # Loading widget
  loading_indicator: ^1.1.0
  # Google fonts
  google_fonts: 0.3.10
  # Pull to refresh
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  retrofit_generator: 1.0.2+2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image_01.png
   - assets/image_02.jpg
   - assets/image_03.jpg
   - assets/image_04.jpg
   - assets/black.jpg
   - assets/box.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/SF-Pro-Text-Regular.ttf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/Calibre-SemiBold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/OpenSans-Regular.ttf

    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/OpenSans-SemiBold.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/OpenSans-Bold.ttf
   
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
